#!/usr/bin/env python
import sys, os, re
commit_msg_filepath = sys.argv[1]
commit_msg_re = '[A-Za-z0-9]{6,144}-[0-9]{1,1000}[A-Za-z0-9]*'

with open(commit_msg_filepath, 'r') as f:
	commit_msg = f.readline()
	result = re.match(commit_msg_re, commit_msg)
	print commit_msg
if result == None:
	print 'invalid commit message'
	print 'your commit needs to have this pattern: {JIRA PROJECT NAME}-{ISSUE NUMBER} {COMMIT MESSAGE}'
	sys.exit(1)
else:
	# GET ISSUE ID ON JIRA CLOUD
	sys.exit(0)
